# Generated by Django 5.0.7 on 2024-11-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='object_id',
            field=models.CharField(editable=False),
        ),
    ]
