volumes:
  userapi_local_postgres_data: {}
  userapi_local_postgres_data_backups: {}
  userapi_local_redis_data: {}

networks:
  proxy-net:
    external: true
  broker-net:
    external: true

services:
#  whoami:
#    image: traefik/whoami
#    container_name: local_whoami
#    networks:
#      - proxy-net
#    labels:
#      - traefik.enable=true
#      - traefik.docker.network=proxy-net
#      - traefik.http.routers.whoami.entrypoints=websecure
#      - traefik.http.routers.whoami.rule=Host(`whoami.darvag.dev`)&&PathRegexp(`/en/users`)
#      - traefik.http.routers.whoami.middlewares=whoami-stripprefix@docker
#      - traefik.http.middlewares.whoami-stripprefix.stripprefix.prefixes=/users
#      - traefik.http.routers.whoami.tls=true

  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: userapi_local_django
    container_name: userapi_local_django
    restart: always
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      - default
      - proxy-net
      - broker-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-net
      - traefik.http.routers.userapi.entrypoints=websecure
      - traefik.http.routers.userapi.rule=(Host(`api.darvag.dev`) || Host(`api.admin.darvag.dev`)) && PathRegexp(`^/((en|fa)/)?users`)
      - traefik.http.routers.userapi.tls=true
      - traefik.http.services.userapi.loadbalancer.server.port=8000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: userapi_production_postgres
    container_name: userapi_local_postgres
    restart: always
    volumes:
      - userapi_local_postgres_data:/var/lib/postgresql/data
      - userapi_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  redis:
    image: docker.io/redis:7.2.5
    container_name: userapi_local_redis
    restart: always
    volumes:
      - userapi_local_redis_data:/data

  celeryworker:
    <<: *django
    image: userapi_local_celeryworker
    container_name: userapi_local_celeryworker
    ports: []
    command: /start-celeryworker
    networks:
      - default
      - broker-net
    labels:
      - traefik.enable=false

  celerybeat:
    <<: *django
    image: userapi_local_celerybeat
    container_name: userapi_local_celerybeat
    ports: []
    command: /start-celerybeat
    networks:
      - default
      - broker-net
    labels:
      - traefik.enable=false

  consumer:
    <<: *django
    image: userapi_local_consumer
    container_name: userapi_local_consumer
    command: python manage.py consumer
    labels:
      - traefik.enable=false

  verificationassigner:
    <<: *django
    image: userapi_local_verificationassigner
    container_name: userapi_local_verificationassigner
    command: python manage.py verificationassigner 10
    labels:
      - traefik.enable=false

  flower:
    <<: *django
    image: userapi_local_flower
    container_name: userapi_local_flower
    command: /start-flower
    networks:
      - default
      - proxy-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy-net
      - traefik.http.routers.userapi-flower.entrypoints=websecure
      - traefik.http.routers.userapi-flower.rule=Host(`userapi-flower.darvag.dev`)
      - traefik.http.routers.userapi-flower.tls=true
      - traefik.http.services.userapi-flower.loadbalancer.server.port=5555
